version: "3.3"

services:
  reverseproxy:
    image: stefanprodan/caddy
    networks:
      - host-net
    environment:
      - CLUSTER01=${CLUSTER01}
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == host1

networks:
  host-net:
    external:
      name: "host"

configs:
  caddy_config:
    file: ./caddy/Caddyfile
