templates:
    - '/etc/alertmanager/*.tmpl'

route:
    receiver: 'slack'
    group_by: ['alertname', 'cluster', 'service', 'instance']
    repeat_interval: 6h
    group_wait: 1m

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: '{{ template "slack.devops.txt" . }}'
            username: evo-prom
            channel: devops-alerts
            api_url: https://hooks.slack.com/services/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
