version: "3.3"

services:
  es1:
    image: stefanprodan/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "TAKE_FILE_OWNERSHIP=true"
      - "network.host=${ESDATA1_IP}"
      - "node.name=${ESDATA1_HOST}"
      - "discovery.zen.ping.unicast.hosts=${ESDATA1_IP},${ESDATA2_IP},${ESDATA3_IP}"
      - "LOGSPOUT=ignore"
    volumes:
      - /usr/share/elasticsearch/data
    networks:
      - host-net
    expose:
      - 9200
      - 9300
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 4G
        reservations:
          memory: 2G
      placement:
        constraints:
          - 'node.hostname==${ESDATA1_HOST}'

  es2:
    image: stefanprodan/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "TAKE_FILE_OWNERSHIP=true"
      - "node.name=${ESDATA2_HOST}"
      - "network.host=${ESDATA2_IP}"
      - "discovery.zen.ping.unicast.hosts=${ESDATA1_IP},${ESDATA2_IP},${ESDATA3_IP}"
      - "LOGSPOUT=ignore"
    volumes:
      - /usr/share/elasticsearch/data
    networks:
      - host-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 4G
        reservations:
          memory: 2G
      placement:
        constraints:
          - 'node.hostname==${ESDATA2_HOST}'

  es3:
    image: stefanprodan/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - "TAKE_FILE_OWNERSHIP=true"
      - "node.name=${ESDATA3_HOST}"
      - "network.host=${ESDATA3_IP}"
      - "discovery.zen.ping.unicast.hosts=${ESDATA1_IP},${ESDATA2_IP},${ESDATA3_IP}"
      - "LOGSPOUT=ignore"
    volumes:
      - /usr/share/elasticsearch/data
    networks:
      - host-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 4G
        reservations:
          memory: 2G
      placement:
        constraints:
          - 'node.hostname==${ESDATA3_HOST}'

  es-router:
    image: stefanprodan/elasticsearch-oss:6.0.0
    environment:
      - "cluster.name=elk"
      - "node.master=false"
      - "node.data=false"
      - "node.ingest=false"
      - "bootstrap.memory_lock=false"
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - "TAKE_FILE_OWNERSHIP=true"
      - "node.name=${ESROUTER_HOST}"
      - "network.host=${ESROUTER_IP}"
      - "discovery.zen.ping.unicast.hosts=${ESDATA1_IP},${ESDATA2_IP},${ESDATA3_IP}"
      - "LOGSPOUT=ignore"
    volumes:
      - /usr/share/elasticsearch/data
    networks:
      - host-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          cpus: '0.20'
          memory: 1G
        reservations:
          memory: 512M
      placement:
        constraints:
          - 'node.hostname==${ESROUTER_HOST}'

  kibana:
    image: stefanprodan/kibana-oss:6.0.0
    environment:
      - "ELASTICSEARCH_URL=http://${ESROUTER_IP}:9200"
      - "LOGSPOUT=ignore"
    networks:
      - net
    ports:
      - 5601:5601
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
      placement:
        constraints:
          - 'node.hostname==${ESROUTER_HOST}'

  logstash:
    image: stefanprodan/logstash-oss:6.0.0
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      - "ESDATA1_IP=${ESDATA1_IP}"
      - "ESDATA2_IP=${ESDATA2_IP}"
      - "ESDATA3_IP=${ESDATA3_IP}"
      - "LOGSPOUT=ignore"
    networks:
      - host-net
    expose:
      - 5000
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  logspout:
    image: stefanprodan/swarm-logspout-logstash:3.2.3
    environment:
      - "ROUTE_URIS=logstash+tcp://localhost:50005"
      - "LOGSPOUT=ignore"
      - "HTTP_PORT=55444"
      - "DOCKER_LABELS=on"
      - "RETRY_STARTUP=on"
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - host-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  curator:
    image: stefanprodan/es-curator-cron:5.4.0
    environment:
      - "PERIOD=daily"
      - "KEEP_DAYS=45"
      - "INDEX_PREFIX=logstash"
    command: "--host ${ESDATA1_IP} --port 9200"
    networks:
      - net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
      placement:
        constraints:
          - 'node.hostname==${ESROUTER_HOST}'

  exporter:
    image: braedon/prometheus-es-exporter:0.4.3
    configs:
      - source: exporter_config
        target: /usr/src/app/exporter.cfg
    command: "-e ${ESROUTER_IP}"
    networks:
      - net
    ports:
      - 9206:9206
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
      placement:
        constraints:
          - 'node.hostname==${ESROUTER_HOST}'

networks:
  host-net:
    external:
      name: "host"
  net:
    driver: overlay
    attachable: true

configs:
  logstash_config:
    file: logstash.yml
  logstash_pipeline:
    file: logstash.pipeline
  exporter_config:
    file: exporter.cfg
